version: '3'

services:
  app:
    image: avishaig1986/labos-home-assignment:v.1.0.0
    ports:
      - "8080:8080"
    networks:
      - app-network

  nginx:
    image: avishaig1986/labos-home-assignment-nginx:v.1.0.0
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge